### ISSUE TITLE
- [ ] Implementación en el Frontend haciendo uso de ReactJS evidenciando la navegación de acuerdo con los prototipos de alta fidelidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_sa_ppi2020#15]

**Comment by JohnFlorez25** [comment]
@MiguelHerrera1 @SamanthaCardona @julianacadavid2 para dentro 8 días deben evidenciar avances en esta actividad donde tengan las interfaces en REACTJS de lo que se validó en el prototipo en alta fidelidad y recomendaciones de los jurados en la socialización.
El código debe estar en el repositorio del proyecto (o sea este repositorio) validar con la profesora @jennymontoya1001  para que les ayuden a realizar este proceso , les dejo un ejemplo de lo que se debe ir evidenciando.
![evidencia-repositorio](https://user-images.githubusercontent.com/22262727/94060456-9f2c4380-fda9-11ea-80c9-36eff58264ad.jpeg)

**Comment by JohnFlorez25** [comment]
@jennymontoya1001 @MiguelHerrera1 @SamanthaCardona @julianacadavid2 aunque hay avances a nivel del repositorio en la carpeta frontend no se ha hecho entraga del video explicando la navegabilidad y el desarrollo realizado en reactjs

**Comment by julianacadavid2** [comment]
@JohnFlorez25  @jennymontoya1001 el link del video ya se encuentra en la wiki
