### ISSUE TITLE
- [ ] Diseño del modelo entidad-relación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_sa_ppi2020#16]

**Comment by JohnFlorez25** [comment]
@MiguelHerrera1 @SamanthaCardona @julianacadavid2 para dentro de 8 días deben tener la evidencia del Modelo entidad relación en la wiki, esta actividad la han venido desarrollando con la profesora @jennymontoya1001  y es ella quien les debe aprobar y validar dicho modelo. Adjunto imagen de ejemplo
![modelo-e-r](https://user-images.githubusercontent.com/22262727/94060514-b2d7aa00-fda9-11ea-997f-a21661705440.png)

**Comment by JohnFlorez25** [comment]
@jennymontoya1001 @MiguelHerrera1 @SamanthaCardona @julianacadavid2 pendiente la evidencia del modelo entidad -relación

**Comment by julianacadavid2** [comment]
@jennymontoya1001 @JohnFlorez25 entrega del modelo entidad relación
