### ISSUE TITLE
- [ ] Construcción de la BD haciendo uso de MySQL

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_sa_ppi2020#19]

**Comment by JohnFlorez25** [comment]
@jennymontoya1001 @MiguelHerrera1 @SamanthaCardona @julianacadavid2 deben crear una carpeta llamada **bd** donde esten alojados los scripts para la creación de la base de datos

**Comment by julianacadavid2** [comment]
@JohnFlorez25  @jennymontoya1001  la construcción del BD esta lista
